// Notification Types
export const NOTIFICATION_TYPES = {
  // Lead Related
  LEAD_ASSIGNED: "LEAD_ASSIGNED",
  LEAD_STATUS_UPDATE: "LEAD_STATUS_UPDATE",
  LEAD_FOLLOWUP_DUE: "LEAD_FOLLOWUP_DUE",

  // Cab Booking Related
  CAB_BOOKING_APPROVED: "CAB_BOOKING_APPROVED",
  CAB_BOOKING_REJECTED: "CAB_BOOKING_REJECTED",
  CAB_BOOKING_ASSIGNED: "CAB_BOOKING_ASSIGNED",
  CAB_BOOKING_REQUEST: "CAB_BOOKING_REQUEST",

  // Vendor Related
  VENDOR_BOOKING_UPDATE: "VENDOR_BOOKING_UPDATE",
  VENDOR_ASSIGNED: "VENDOR_ASSIGNED",

  // MOU Related
  MOU_APPROVED: "MOU_APPROVED",
  MOU_REJECTED: "MOU_REJECTED",
  MOU_PENDING: "MOU_PENDING",

  // User/Role Related
  USER_ROLE_CHANGED: "USER_ROLE_CHANGED",
  USER_UPDATED: "USER_UPDATED",
  USER_WELCOME: "USER_WELCOME",
  USER_ASSIGNED: "USER_ASSIGNED",
  NEW_USER_ADDED: "NEW_USER_ADDED",
  ROLE_CREATED: "ROLE_CREATED",
  ROLE_UPDATED: "ROLE_UPDATED",

  // Property Related
  PROPERTY_UPLOADED: "PROPERTY_UPLOADED",
  PROPERTY_STATUS_UPDATE: "PROPERTY_STATUS_UPDATE",

  // System/General
  SYSTEM_ANNOUNCEMENT: "SYSTEM_ANNOUNCEMENT",
  REMINDER: "REMINDER",
  BULK_UPLOAD_COMPLETE: "BULK_UPLOAD_COMPLETE",
  EMAIL_SENT: "EMAIL_SENT",
};

// Notification Statuses
export const NOTIFICATION_STATUS = {
  PENDING: "PENDING",
  DELIVERED: "DELIVERED",
  READ: "READ",
  ARCHIVED: "ARCHIVED",
  EXPIRED: "EXPIRED",
};

// Priorities
export const NOTIFICATION_PRIORITY = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  URGENT: "URGENT",
};

// Action Types
export const NOTIFICATION_ACTIONS = {
  CLICKED: "CLICKED",
  DISMISSED: "DISMISSED",
  ACTED_UPON: "ACTED_UPON",
  IGNORED: "IGNORED",
};

// Channels
export const NOTIFICATION_CHANNELS = {
  IN_APP: "inApp",
  EMAIL: "email",
};

export const DEFAULT_RETENTION_DAYS = {
  READ: 7,
  UNREAD: 30,
  ARCHIVED: 90,
};
