import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../contexts/AuthContext";
import { PermissionsProvider } from "../contexts/PermissionsContext";
import MuiRootProvider from "../components/ui/MuiRootProvider";
import LoginWrapper from "../components/ui/LoginWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Inrext",
  description: "Generated by Inrext Tech",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MuiRootProvider>
          <AuthProvider>
            <LoginWrapper>{children}</LoginWrapper>
          </AuthProvider>
        </MuiRootProvider>
      </body>
    </html>
  );
}
