export const cardStyles = {
  container: "group relative w-full rounded-2xl p-4 flex flex-col gap-3 min-w-0 bg-white border border-gray-100 shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all duration-300 overflow-hidden",
  header: "flex items-start justify-between relative",
  profileInfo: "flex items-center gap-4 flex-1 min-w-0",
  avatarWrapper: "relative",
  avatarImage: "w-14 h-14 rounded-full object-cover shadow-md ring-2 ring-white",
  avatarPlaceholder: "w-14 h-14 rounded-full flex items-center justify-center font-bold text-xl bg-gradient-to-br from-blue-600 to-indigo-700 text-white shadow-lg ring-2 ring-white",
  nameSection: "flex-1 min-w-0",
  nameTitle: "text-lg font-bold text-gray-900 leading-tight truncate group-hover:text-blue-600 transition-colors",
  designationText: "text-sm text-blue-600 font-semibold truncate mt-1",
  actionContainer: "flex flex-col gap-0.5 absolute bottom-4 right-4 z-10",
  actionButton: "text-gray-400 hover:text-blue-600 hover:bg-blue-50 transition-all active:scale-90",
  metadataSection: "space-y-1 relative border-t border-gray-50 pt-2",
  metadataItem: "flex items-center gap-2 text-gray-400",
  metadataIcon: "w-4 h-4",
  metadataValue: "text-sm truncate font-medium text-gray-700",
  orgSection: "flex flex-col gap-1.5 pt-1 border-t border-gray-50 mt-0.5 pb-0.5",
  orgItem: "flex items-center gap-2 text-gray-400",
  orgIcon: "w-4 h-4",
  orgLabel: "text-xs font-semibold uppercase tracking-wider text-gray-400",
  orgValue: "text-sm font-medium text-gray-700 truncate",
};
